= Alert rule: APPUiOCloudInvoiceGenerationFailed

include::partial$runbooks/contribution_note.adoc[]

== icon:glasses[] Overview

APPUiO Cloud Reporting failed while trying to generate invoices.
Invoices might be incomplete or missing.
Remove any obstacles and rerun the job.

[IMPORTANT]
====
The job isn't idempotent.
Rerunning the job, can leave duplicates which need to be cleaned up.
====

== icon:bug[] Steps for debugging

. Identify source of failure
* Check for missing data indicated by the alert rule xref:runbooks/APPUiOCloudReportingMissingData.adoc[APPUiOCloudReportingMissingData].
* Check logs for other issues.
  Look out for connectivity issues (for example between the job and the ERP).
+
[source,bash]
----
kubectl -n appuio-cloud-reporting logs $(kubectl -n appuio-cloud-reporting get job -l cron-job-name=generate-invoices --field-selector status.successful=0 -o name | tail -n1) --all-containers
----

. Remove any obstacles
+
Use the findings from the previous step to remove any obstacles causing the job to fail again.

. Rerun job
+
[source,bash]
----
name="generate-invoices-manual-$($(command -v gdate || command -v date) +%s)"
kubectl --as cluster-admin -n appuio-cloud-reporting create job --from=cronjob/generate-invoices "${name}"
kubectl -n appuio-cloud-reporting logs "job/${name}"
----

. Check ERP for duplicates
+
In the ERP, search for the generated invoices.
Remove all duplicates.
+
[NOTE]
====
Invoices with status Draft can be removed without issues.
For other states, check with finance.
They might redo some modifications.
====
+
[TIP]
====
Use the advanced search to search "APPUiO Cloud <month> <year>" in the field `Reference/Description`.
Then sort by `Customer`.
This makes spotting duplicates easier.
====

. Clean up
+
Remove all failed check-missing jobs to clear the alert.
+
[source,bash]
----
kubectl -n appuio-cloud-reporting delete $(kubectl -n appuio-cloud-reporting get job -l cron-job-name=generate-invoices --field-selector status.successful=0 -o name)
----
