= Parameters

The parent key for all of the following parameters is `appuio_cloud_reporting`.

== `namespace`

[horizontal]
type:: string
default:: `${_instance}`

The namespace in which to deploy this component.


== `images`

[horizontal]
type:: dictionary
default:: https://github.com/appuio/component-appuio-cloud-reporting/blob/master/class/defaults.yml[See `class/defaults.yml].

Dictionary containing the container images used by this component.


=== `images.reporting`

[horizontal]
type:: dictionary

The image used for managing data in the reporting database.


=== `images.erp_adapter`

[horizontal]
type:: dictionary

The image used for creating invoices and syncing target fields.


== `schedules`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
backfill: '15 * * * *'
check_missing: '30 8-14 * * *'
invoice: '0 10 1 * *'
----

Dictionary managing the schedules of the periodic jobs (implemented as Kubernetes CronJobs).

== `development_mode`

[horizontal]
type:: boolean
default:: `false`

This parameter allows to enable development mode for the component.
The component prevents periodic jobs from being disabled, unless development mode is active.

== `schedules_suspend`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
backfill: false
check_missing: false
invoice: false
----

This parameter allows users to selectively suspend one or more of the periodic jobs.

A suspended CronJob still exists on the cluster, but no new jobs are created based on the CronJob's schedule.

[IMPORTANT]
====
Never use this parameter to disable CronJobs because they trigger alerts.
Instead investigate why the alerts are triggered, and resolve the actual cause, such as missing data in the billing database.

By disabling one or more of the periodic jobs, you'll most likely break the usage-based billing for the APPUiO Cloud instance.
Breaking the usage-based billing will lead to lost income for the APPUiO Cloud instance.
====

== `database`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
host: null
port: 5432
name: appuio-cloud-reporting
username: appuio-cloud-reporting
password: null
parameters: ''
----

Dictionary managing the connection to the reporting database.


== `prometheus.url`

[horizontal]
type:: string
default:: `null`

URL used to connect with the Prometheus/Thanos Instance.


== `prometheus.org_id`

[horizontal]
type:: string
default:: `null`

If set, this value is sent as the `X-Scope-OrgID` header in all requests to Prometheus.


== `erp_adapter.url`

[horizontal]
type:: string
default:: `null`

URL used to connect with the ERP Instance.
For Odoo the URL must be in the format of `https://user:pass@host[:port]/db-name`.


== `erp_adapter.invoice_title`

[horizontal]
type:: string
default:: `"APPUiO Cloud"`

Invoice title to be used by the ERP adapter when generating invoices.


== `backfill.queries`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
appuio_cloud_memory: true
appuio_cloud_loadbalancer: true
appuio_cloud_persistent_storage: true
appcat_postgresql_vshn_standalone: true
----

Queries to use when backfilling metrics data.
`true` enables the query, every other value disables the query.
Every query is run in its own CronJob.

Check the reporting database for possible queries.
Currently known queries are `appuio_cloud_memory`, `appuio_cloud_loadbalancer`, `appuio_cloud_persistent_storage`, and `appcat_postgresql_vshn_standalone`.


== `network_policies.target_namespaces`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
appuio-reporting-database: true
appuio-thanos: true
----

Injects a network policy into the target namespace given by the key, allowing communication to the namespace.

[NOTE]
This is a workaround and the parameter will disappear once we've a more native way to manage network policies with Project Syn.


== `monitoring.enabled`

[horizontal]
type:: boolean
default:: `true`

The component creates Prometheus and Alertmanager objects if enabled.


== `monitoring.alerts`

[horizontal]
type:: dictionary
example::
+
[source,yaml]
----
APPUiOCloudReportingDidSomething:
  enabled: false
  rule:
    annotations:
      description: APPUiOCloudReporting did something.
      message: APPUiOCloudReporting did something.
      runbook: https://hub.syn.tools/appuio-cloud-reporting/runbooks/APPUiOCloudReportingDidSomething.html
    expr: |
      appuio_cloud_reporting_doing_something > 1
    for: 10m
    labels:
      severity: warning
----

Alerts monitoring the cloud reporting cron jobs.


== `tenantmapping`

[horizontal]
type:: dictionary

Configuration for the tenant mapping job.
The job is responsible for mapping the tenants source (organization) to the target in the ERP (billing entity).


== `tenantmapping.dry_run`

[horizontal]
type:: boolean
default:: `true`

Doesn't commit the tenant mapping to the database if set to `true`.


== `tenantmapping.metrics_selector`

[horizontal]
type:: boolean
default:: `namespace="appuio-control-api-production"`

Further narrows down the metrics to be considered for the tenant mapping.
Prometheus selector syntax (`test="asd"`) is used.


== Example

[source,yaml]
----
schedules:
  invoice: '0 12 1 * *'

database:
  host: reporting-database.appuio.cloud
  port: 5432
  name: reporting-database
  username: reporting-user
  password: ?{vaultkv:${cluster:tenant}/${cluster:name}/appuio-cloud-reporting/reporting-database-password}

erp_adapter:
  url: ?{vaultkv:${cluster:tenant}/${cluster:name}/appuio-cloud-reporting/erp-url}

prometheus:
  url: http://thanos-query.appuio-thanos.svc:9090
----
